//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("faksModel", "FK_student_mjesto", "mjesto", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(faksModel.mjesto), "student", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(faksModel.student), true)]

#endregion

namespace faksModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class faksEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new faksEntities object using the connection string found in the 'faksEntities' section of the application configuration file.
        /// </summary>
        public faksEntities() : base("name=faksEntities", "faksEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new faksEntities object.
        /// </summary>
        public faksEntities(string connectionString) : base(connectionString, "faksEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new faksEntities object.
        /// </summary>
        public faksEntities(EntityConnection connection) : base(connection, "faksEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<mjesto> mjesto
        {
            get
            {
                if ((_mjesto == null))
                {
                    _mjesto = base.CreateObjectSet<mjesto>("mjesto");
                }
                return _mjesto;
            }
        }
        private ObjectSet<mjesto> _mjesto;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<student> student
        {
            get
            {
                if ((_student == null))
                {
                    _student = base.CreateObjectSet<student>("student");
                }
                return _student;
            }
        }
        private ObjectSet<student> _student;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the mjesto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomjesto(mjesto mjesto)
        {
            base.AddObject("mjesto", mjesto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the student EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostudent(student student)
        {
            base.AddObject("student", student);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="faksModel", Name="mjesto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class mjesto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new mjesto object.
        /// </summary>
        /// <param name="pbr">Initial value of the pbr property.</param>
        public static mjesto Createmjesto(global::System.Int32 pbr)
        {
            mjesto mjesto = new mjesto();
            mjesto.pbr = pbr;
            return mjesto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pbr
        {
            get
            {
                return _pbr;
            }
            set
            {
                if (_pbr != value)
                {
                    OnpbrChanging(value);
                    ReportPropertyChanging("pbr");
                    _pbr = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pbr");
                    OnpbrChanged();
                }
            }
        }
        private global::System.Int32 _pbr;
        partial void OnpbrChanging(global::System.Int32 value);
        partial void OnpbrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String naziv
        {
            get
            {
                return _naziv;
            }
            set
            {
                OnnazivChanging(value);
                ReportPropertyChanging("naziv");
                _naziv = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("naziv");
                OnnazivChanged();
            }
        }
        private global::System.String _naziv;
        partial void OnnazivChanging(global::System.String value);
        partial void OnnazivChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("faksModel", "FK_student_mjesto", "student")]
        public EntityCollection<student> student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<student>("faksModel.FK_student_mjesto", "student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<student>("faksModel.FK_student_mjesto", "student", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="faksModel", Name="student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class student : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new student object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static student Createstudent(global::System.Int32 id)
        {
            student student = new student();
            student.id = id;
            return student;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ime
        {
            get
            {
                return _ime;
            }
            set
            {
                OnimeChanging(value);
                ReportPropertyChanging("ime");
                _ime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ime");
                OnimeChanged();
            }
        }
        private global::System.String _ime;
        partial void OnimeChanging(global::System.String value);
        partial void OnimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String prezime
        {
            get
            {
                return _prezime;
            }
            set
            {
                OnprezimeChanging(value);
                ReportPropertyChanging("prezime");
                _prezime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("prezime");
                OnprezimeChanged();
            }
        }
        private global::System.String _prezime;
        partial void OnprezimeChanging(global::System.String value);
        partial void OnprezimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> pbr
        {
            get
            {
                return _pbr;
            }
            set
            {
                OnpbrChanging(value);
                ReportPropertyChanging("pbr");
                _pbr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pbr");
                OnpbrChanged();
            }
        }
        private Nullable<global::System.Int32> _pbr;
        partial void OnpbrChanging(Nullable<global::System.Int32> value);
        partial void OnpbrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lozinka
        {
            get
            {
                return _lozinka;
            }
            set
            {
                OnlozinkaChanging(value);
                ReportPropertyChanging("lozinka");
                _lozinka = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lozinka");
                OnlozinkaChanged();
            }
        }
        private global::System.String _lozinka;
        partial void OnlozinkaChanging(global::System.String value);
        partial void OnlozinkaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("faksModel", "FK_student_mjesto", "mjesto")]
        public mjesto mjesto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mjesto>("faksModel.FK_student_mjesto", "mjesto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mjesto>("faksModel.FK_student_mjesto", "mjesto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<mjesto> mjestoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mjesto>("faksModel.FK_student_mjesto", "mjesto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<mjesto>("faksModel.FK_student_mjesto", "mjesto", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
